      MODULE YOWPARAM

      IMPLICIT NONE

!*    ** *PARAM*  GENERAL GRID SIZE INFORMATION.

      INTEGER NANG 
      INTEGER NFRE

!*     VARIABLE.   TYPE.     PURPOSE.
!       ---------   -------   --------.
!
!      *NANG*      INTEGER   NUMBER OF ANGLES.
!      *NFRE*      INTEGER   NUMBER OF FREQUENCIES.

! ----------------------------------------------------------------------

      END MODULE YOWPARAM
