#!/bin/sh
set -ex
. ${0%/*}/.dirset
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/psource.mk $OBJDIR
cd $OBJDIR
make -f psource.mk psource
mv psource $EXECDIR
rm -f psource.mk
