#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load compilers/intel/2020.1.217
module load intelmpi/2020.1.217
module load netcdf
    
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/ptime.mk $OBJDIR
cd $OBJDIR
make -f ptime.mk ptime
mv ptime $EXECDIR
rm -f ptime.mk
