#!/bin/bash
#++

if [ "$1" == strand ]; then
        #### STRAND - Intel2020 ####
        module purge
        module load compilers/intel/2020.1.217
        module load intelmpi/2020.1.217
        module load netcdf

        export FC=mpiifort
        export FFLAGS='-heap-arrays 64 -fp-model precise -O3'
        NCDFDIR=/project/opt/software/netcdf/4.7.0/intel
        NCDFIN=-I${NCDFDIR}/include
        NCDFLIB=-L${NCDFDIR}/lib
        NCDFFLAGS='-lnetcdf -lnetcdff'
        export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS}"

        echo export PRODADMDIR=$(dirname $(pwd)) > .dirset


elif [ "$1" == strand-oneAPI ]; then
        #### STRAND - oneAPI ####
        module purge
        module load compilers/intel/oneAPI/2021.2.0
        module load netcdf

        export FC=mpiifort
        export FFLAGS='-heap-arrays 64 -fp-model precise -O3'
        NCDFDIR=/project/opt/software/netcdf/4.9.2/intel_oneAPI
        NCDFIN=-I${NCDFDIR}/include
        NCDFLIB=-L${NCDFDIR}/lib
        NCDFFLAGS='-lnetcdf -lnetcdff'
        export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS}"

        echo export PRODADMDIR=$(dirname $(pwd)) > .dirset


elif [ "$1" == levante ]; then
        #### LEVANTE - OpenMPI (wk.make.LEVANTE) ####
        module purge
        module load openmpi/4.1.2-intel-2021.5.0
        module load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0
        module load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0

        export FC=mpifort
        export FFLAGS="-heap-arrays 64 -fp-model precise" #"-heap-arrays 64 -g -traceback -check bounds"
        #export MPIIN="-I/sw/spack-levante/openmpi-4.1.2-yfwe6t/include"
        export NCDFIN="-I/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/include"
        export NCDFLIB="-L/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/lib -Wl,-rpath,/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/lib"
        export NCDFFLAGS="-lnetcdff"

        export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS}"

        echo export PRODADMDIR=$(dirname $(pwd)) > .dirset


elif [ "$1" == levante-oneAPI ]; then
        #### LEVANTE - oneAPI (NAAM) ####
        module purge
        module load intel-oneapi-compilers/2022.0.1-gcc-11.2.0
        module load intel-oneapi-mpi/2021.5.0-intel-2021.5.0
        module load netcdf-c/4.8.1-intel-oneapi-mpi-2021.5.0-intel-2021.5.0
        module load netcdf-fortran/4.5.3-intel-oneapi-mpi-2021.5.0-intel-2021.5.0

        export FC=mpiifort
        export FFLAGS="-heap-arrays 64 -fp-model precise" #"-heap-arrays 64 -g -traceback -check bounds"
        export NCDFIN="-I/sw/spack-levante/netcdf-fortran-4.5.3-r5r3ev/include"
        export NCDFLIB="-L/sw/spack-levante/netcdf-fortran-4.5.3-r5r3ev/lib -Wl,-rpath,/sw/spack-levante/netcdf-fortran-4.5.3-r5r3ev/lib"
        export NCDFFLAGS="-lnetcdff"
        #export HDF5IN="-I/sw/spack-levante/hdf5-1.12.1-jmeuy3/include"
        #export HDF5LIB="-L/sw/spack-levante/hdf5-1.12.1-jmeuy3/lib"

        export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS}"
        #export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS} ${HDF5IN} ${HDF5LIB} ${HDFFLAGS}"

        echo export PRODADMDIR=$(dirname $(pwd)) > .dirset


elif [ "$1" == levante-GCC ]; then
        #### LEVANTE - GCC ####
        module purge
        module load openmpi/4.1.2-gcc-11.2.0
        module load netcdf-c/4.8.1-openmpi-4.1.2-gcc-11.2.0
        module load netcdf-fortran/4.5.3-openmpi-4.1.2-gcc-11.2.0

        export FC=mpifort
        export FFLAGS=" " #"-march=native" #"-heap-arrays 64 -g -traceback -check bounds"
        #export MPIIN="-I/sw/spack-levante/openmpi-4.1.2-mnmady/include"
        export NCDFIN="-I/sw/spack-levante/netcdf-fortran-4.5.3-jlxcfz/include"
        export NCDFLIB="-L/sw/spack-levante/netcdf-fortran-4.5.3-jlxcfz/lib -Wl,-rpath,/sw/spack-levante/netcdf-fortran-4.5.3-jlxcfz/lib"
        export NCDFFLAGS="-lnetcdff"
        #export HDF5IN="-I/sw/spack-levante/hdf5-1.12.1-kxfaux/include"
        #export HDF5LIB="-L/sw/spack-levante/hdf5-1.12.1-kxfaux/lib"

        export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS}"
        #export LDOPT="${NCDFIN} ${NCDFLIB} ${NCDFFLAGS} ${HDF5IN} ${HDF5LIB} ${HDFFLAGS}"

        echo export PRODADMDIR=$(dirname $(pwd)) > .dirset


elif [ "$1" == first ]; then
        echo '=== WARNING: create_binaries called from script (wk.make*) ==='
        echo '===          No further variables set or exported !        ==='


else
        echo '!!! ERROR: No environment specified !!! '
        exit
fi

if [ ! -d ../obj ]; then mkdir -p ../obj; fi
if [ ! -d ../abs ]; then mkdir -p ../abs; fi
#
# compile
#
echo '==== Compilation Started ==='
(cd ../src/mod;     ln -sf wam_oasis_inactive_module.f90 wam_oasis_module.f90)
./make_modules1
./make_modules2
./make_preproc
./make_chief
./make_print
./make_netcdf
#
# create binaries
#
echo '==== Building Binaries Started ==='
./build_preproc
./build_wam
./build_pgrid
./build_pspec
./build_ptime
./build_ptime_S
./build_pnetcdf
./build_psource
#
