#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/chief

modfile="chief wavemdl initmdl read_wam_user print_wam_status read_wind_input \
read_current_input wamodel read_boundary_input read_ice_input jafu \
read_topo_input readsat"

cd $path_o
cp ${NETCDFHOME}/include/netcdf.inc .
cp ${NETCDFHOME}/include/netcdf.mod .
cp ${NETCDFHOME}/include/typesizes.mod .

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   $FC ${fflags} -c ${code}.f90 -L/user/lib64
   rm -f ${code}.f90
done
