#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/print

modfile="wam_rad_netcdf_module make_rad_netcdf dtsec"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   $FC -c ${code}.f90 -I$NETCDFHOME/include -L$NETCDFHOME/lib -lnetcdf -lnetcdff
   rm -f ${code}.f90
done
