#!/bin/bash
#
#==>  WAM post-processing pnetcdf
#
#     Arno Behrens (March January 2016)
#
#SBATCH --job-name=pnetcdf
#SBATCH --partition=short.p
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=pnetcdf.o%j
#SBATCH --error=pnetcdf.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf

# module load intel/oneapi-2022
module load netcdf/4.6.1-openmpi-1.10.3
module load openmpi/1.10.3-intel-2017
#
set -k
WAMDIR=/home/bulatsa/mricker/SeaReCap
WORK=/work/bulatsa/mricker/SeaReCap
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Fine_1/JAN/nlnetcdf NETCDF_User
cp ${WAMDIR}/abs/pnetcdf pnetcdf.exe
#
srun --mpi=pmi2 ./pnetcdf.exe
#
mv pnetcdf_prot ${WAMDIR}/dayfiles/pnetcdf_prot_fine_1
mv WAVE* ../fine_1
rm NETCDF_User pnetcdf.exe
#
# ===================================================================
#  NETCDF FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PNETCDF.
# ===================================================================
#
