#!/bin/bash
#
#==>  WAM post-processing pgrid
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=pgrid
#SBATCH --partition=short.p
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=wam.o%j
#SBATCH --error=wam.e%j
#
# module load compilers/intel/2019.4.243
# module load intelmpi/2019.4.243
# module load netcdf

# module load intel/oneapi-2022
module load netcdf/4.6.1-openmpi-1.10.3
module load openmpi/1.10.3-intel-2017
#
set -k
WAMDIR=/home/bulatsa/mricker/SeaReCap
WORK=/work/bulatsa/mricker/SeaReCap
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Coarse_Grid/JAN/Grid_User .
cp ${WAMDIR}/abs/pgrid pgrid.exe
#
./pgrid.exe
mv Grid_Prot ${WAMDIR}/dayfiles/pgrid_prot_coarse_JAN
rm Grid_User pgrid.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
