#!/bin/bash
#
#==>  WAM post-processing pgrid
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=pgrid
#SBATCH --partition=pCluster
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:30:00
##SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=jpgrid.o%j
#SBATCH --error=jpgrid.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
#
set -k
WAMDIR=/gpfs/home/ricker/WAM/WAM_Cycle7_test
WORK=/gpfs/work/ricker/storage/WAM/WAM_Cycle7_test
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Grid_User .
cp ${WAMDIR}/abs/pgrid pgrid.exe
#
./pgrid.exe
mv Grid_Prot ${WAMDIR}/dayfiles/pgrid_prot_coarse_ST6
rm Grid_User pgrid.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
