#!/bin/sh
#
#==>  WAM post-processing pnetcdf
#
#     Arno Behrens (March January 2016)
#
#SBATCH --job-name=pnetcdf
#SBATCH --partition=pCluster
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
##SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=pnetcdf.o%j
#SBATCH --error=pnetcdf.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
#
set -k
WAMDIR=/gpfs/home/ricker/WAM/WAM_Cycle7_test
WORK=/gpfs/work/ricker/storage/WAM/WAM_Cycle7_test
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/nlnetcdf NETCDF_User
cp ${WAMDIR}/abs/pnetcdf pnetcdf.exe
#
srun --mpi=pmi2 ./pnetcdf.exe
#
mv pnetcdf_prot ${WAMDIR}/dayfiles/pnetcdf_prot_coarse_ST6
mv WAVE* ../coarse/ST6/
rm NETCDF_User pnetcdf.exe
#
# ===================================================================
#  NETCDF FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PNETCDF.
# ===================================================================
#
