#!/bin/bash
#
#     Arno Behrens (May 2019)
#
#==>  WAM post-processing pspec
#
#SBATCH --job-name=pspec
#SBATCH --partition=short.p
#SBATCH --ntasks=1
#SBATCH --time=00:05:00
#SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=pspec.o%j
#SBATCH --error=pspec.e%j
#
# module load compilers/intel/2019.4.243
# module load intelmpi/2019.4.243
# module load netcdf

# module load intel/oneapi-2022
module load netcdf/4.6.1-openmpi-1.10.3
module load openmpi/1.10.3-intel-2017
#
set -k
WAMDIR=/home/bulatsa/mricker/SeaReCap
WORK=/work/bulatsa/mricker/SeaReCap
#
cd ${WORK}/tempsg
cp ${WAMDIR}/const/Coarse_Grid/JAN/Spectra_User .
cp ${WAMDIR}/abs/pspec pspec.exe
#
./pspec.exe
#
mv Spectra_Prot ${WAMDIR}/dayfiles/pspec_prot_coarse_JAN
rm Spectra_User pspec.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
