#!/bin/bash
#
#==>  WAM post-processing ptime_s
#
#     Arno Behrens (July 2015)
#
#SBATCH --job-name=ptime_s
#SBATCH --partition=short.p
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=ptime_s.o%j
#SBATCH --error=ptime_s.e%j
#
# module load compilers/intel/2019.4.243
# module load intelmpi/2019.4.243
# module load netcdf

# module load intel/oneapi-2022
module load netcdf/4.6.1-openmpi-1.10.3
module load openmpi/1.10.3-intel-2017
#
set -k
WAMDIR=/gpfs/home/behrens/WAM_Cycle_6
WORK=/gpfs/work/behrens/WAM_Cycle_6
#
cd ${WORK}/tempsg
cp ${WAMDIR}/const/Coarse_Grid/JAN/Time_User_S .
cp ${WAMDIR}/abs/ptime_S ptime_S.exe
#
./ptime_S.exe
mv Time_Prot_S ${WAMDIR}/dayfiles/ptime_S_prot_coarse_JAN
rm Time_User_S ptime_S.exe 
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PTIME.
# ===================================================================
#
