#!/bin/bash
#
#==>  WAM model run
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=TS_Wave
#SBATCH --partition=pCluster
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=00:30:00
##SBATCH --mail-type=FAIL
##SBATCH --account=cluster
#SBATCH --output=wam.o%j
#SBATCH --error=wam.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
#
set +k
cdir=/gpfs/home/ricker/WAM/WAM_Cycle7_test
work=/gpfs/work/ricker/storage/WAM/WAM_Cycle7_test
#
cd ${work}/tempsg
cp ${cdir}/const/WAM_User .
cp ${work}/work/Grid_info_COARSE_GRID .
cp ${cdir}/const/WIND_INPUT.DAT .
cp ${cdir}/const/ICE_INPUT.DAT .
cp ${cdir}/const/CURRENT_INPUT.DAT .
cp ${cdir}/const/TOPO_INPUT.DAT .
cp ${cdir}/const/OBS* .
#
cp ${cdir}/abs/wam wam.exe
srun --mpi=pmi2 ./wam.exe
#
cp logfile.0 ${cdir}/dayfiles/wam_prot_coarse_ST6
rm OBS* ICE_INPUT.DAT CURRENT_INPUT.DAT TOPO_INPUT.DAT
rm wam.exe WAM_User Grid_info_COARSE_GRID WIND_INPUT.DAT logfile.*
mv BLS* MAP* OUT* C* ../coarse/ST6/
#
